import type {
  User,
  Organization,
  Location,
  Department,
  Region,
  AssetType,
  Asset,
  AssetMovement,
  DashboardStats,
  WorkflowRequest,
  Notification,
  AuditLog,
  AssetRequest,
  ApprovalRoutingRule,
} from "./types";

// Mock Current User - HO Admin with final approval authority
export const currentUser: User = {
  id: "user-1",
  name: "John Anderson",
  email: "john@acmecorp.com",
  role: "ho_admin",
  organizationId: "org-1",
  avatar: undefined,
  canApproveTransfers: true,
  canApproveDisposals: true,
  canApproveBuybacks: true,
};

// Mock Organizations
export const organizations: Organization[] = [
  {
    id: "org-1",
    name: "ACME Corporation",
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "org-2",
    name: "GlobalTech Industries",
    createdAt: new Date("2023-03-22"),
  },
];

// Mock Locations
export const locations: Location[] = [
  {
    id: "loc-1",
    organizationId: "org-1",
    name: "Headquarters",
    address: "123 Main Street, New York, NY 10001",
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "loc-2",
    organizationId: "org-1",
    name: "West Coast Office",
    address: "456 Market Street, San Francisco, CA 94105",
    createdAt: new Date("2023-02-10"),
  },
  {
    id: "loc-3",
    organizationId: "org-1",
    name: "Chicago Branch",
    address: "789 Michigan Ave, Chicago, IL 60611",
    createdAt: new Date("2023-04-05"),
  },
];

// Mock Departments
export const departments: Department[] = [
  {
    id: "dept-1",
    locationId: "loc-1",
    name: "Engineering",
    reportingPersonId: "user-2",
    hodId: "user-3",
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "dept-2",
    locationId: "loc-1",
    name: "Marketing",
    reportingPersonId: "user-4",
    hodId: "user-5",
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "dept-3",
    locationId: "loc-2",
    name: "Sales",
    reportingPersonId: "user-6",
    hodId: "user-7",
    createdAt: new Date("2023-02-10"),
  },
  {
    id: "dept-4",
    locationId: "loc-1",
    name: "Human Resources",
    reportingPersonId: "user-8",
    hodId: "user-9",
    createdAt: new Date("2023-01-20"),
  },
  {
    id: "dept-5",
    locationId: "loc-3",
    name: "Operations",
    reportingPersonId: "user-10",
    hodId: "user-11",
    createdAt: new Date("2023-04-10"),
  },
];

// Mock Regions
export const regions: Region[] = [
  {
    id: "region-1",
    organizationId: "org-1",
    name: "East Region",
    approverId: "user-12",
    locationIds: ["loc-1"],
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "region-2",
    organizationId: "org-1",
    name: "West Region",
    approverId: "user-13",
    locationIds: ["loc-2"],
    createdAt: new Date("2023-02-10"),
  },
  {
    id: "region-3",
    organizationId: "org-1",
    name: "Central Region",
    approverId: "user-14",
    locationIds: ["loc-3"],
    createdAt: new Date("2023-04-05"),
  },
];

// Mock Asset Types
export const assetTypes: AssetType[] = [
  {
    id: "type-1",
    name: "Laptop",
    description: "Portable computing devices",
    hasExpiry: false,
    isRechargeable: true,
    isOneTimeUse: false,
    isMovable: true,
    requiresAssignment: true,
    properties: [
      { id: "prop-1", name: "Brand", type: "text", required: true },
      { id: "prop-2", name: "Model", type: "text", required: true },
      { id: "prop-3", name: "RAM (GB)", type: "number", required: true },
      { id: "prop-4", name: "Storage (GB)", type: "number", required: true },
      {
        id: "prop-5",
        name: "Operating System",
        type: "dropdown",
        required: true,
        options: ["Windows 11", "macOS", "Linux"],
      },
    ],
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "type-2",
    name: "Software License",
    description: "Digital software licenses",
    hasExpiry: true,
    isRechargeable: false,
    isOneTimeUse: false,
    isMovable: false,
    requiresAssignment: true,
    properties: [
      { id: "prop-6", name: "Vendor", type: "text", required: true },
      { id: "prop-7", name: "License Key", type: "text", required: true },
      { id: "prop-8", name: "Seats", type: "number", required: true },
      { id: "prop-9", name: "Renewal Date", type: "date", required: true },
    ],
    createdAt: new Date("2023-01-20"),
  },
  {
    id: "type-3",
    name: "Office Furniture",
    description: "Desks, chairs, and other office furniture",
    hasExpiry: false,
    isRechargeable: false,
    isOneTimeUse: false,
    isMovable: true,
    requiresAssignment: false,
    properties: [
      {
        id: "prop-10",
        name: "Type",
        type: "dropdown",
        required: true,
        options: ["Desk", "Chair", "Cabinet", "Shelf", "Table"],
      },
      { id: "prop-11", name: "Material", type: "text", required: false },
      { id: "prop-12", name: "Color", type: "text", required: false },
    ],
    createdAt: new Date("2023-02-01"),
  },
  {
    id: "type-4",
    name: "Printer Cartridge",
    description: "Consumable printer supplies",
    hasExpiry: true,
    isRechargeable: false,
    isOneTimeUse: true,
    isMovable: true,
    requiresAssignment: false,
    properties: [
      { id: "prop-13", name: "Color", type: "dropdown", required: true, options: ["Black", "Cyan", "Magenta", "Yellow"] },
      { id: "prop-14", name: "Compatible Printer", type: "text", required: true },
      { id: "prop-15", name: "Page Yield", type: "number", required: false },
    ],
    createdAt: new Date("2023-02-15"),
  },
];

// Mock Assets
export const assets: Asset[] = [
  {
    id: "asset-1",
    assetTypeId: "type-1",
    assetType: assetTypes[0],
    name: "MacBook Pro 16-inch",
    serialNumber: "C02XL0THJGH7",
    category: "it",
    status: "assigned",
    organizationId: "org-1",
    locationId: "loc-1",
    departmentId: "dept-1",
    assignedToId: "user-2",
    purchaseDate: new Date("2023-06-15"),
    warrantyEndDate: new Date("2026-06-15"),
    properties: {
      Brand: "Apple",
      Model: "MacBook Pro 16-inch M3",
      "RAM (GB)": 32,
      "Storage (GB)": 1024,
      "Operating System": "macOS",
    },
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "asset-2",
    assetTypeId: "type-1",
    assetType: assetTypes[0],
    name: "Dell XPS 15",
    serialNumber: "DELL-XPS-2023-001",
    category: "it",
    status: "available",
    organizationId: "org-1",
    locationId: "loc-1",
    departmentId: "dept-1",
    purchaseDate: new Date("2023-08-20"),
    warrantyEndDate: new Date("2026-08-20"),
    properties: {
      Brand: "Dell",
      Model: "XPS 15 9530",
      "RAM (GB)": 16,
      "Storage (GB)": 512,
      "Operating System": "Windows 11",
    },
    createdAt: new Date("2023-08-20"),
    updatedAt: new Date("2023-12-05"),
  },
  {
    id: "asset-3",
    assetTypeId: "type-2",
    assetType: assetTypes[1],
    name: "Microsoft 365 Enterprise",
    category: "it",
    status: "assigned",
    organizationId: "org-1",
    locationId: "loc-1",
    departmentId: "dept-1",
    expiryDate: new Date("2025-03-15"),
    properties: {
      Vendor: "Microsoft",
      "License Key": "XXXXX-XXXXX-XXXXX-XXXXX",
      Seats: 50,
      "Renewal Date": "2025-03-15",
    },
    createdAt: new Date("2023-03-15"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: "asset-4",
    assetTypeId: "type-2",
    assetType: assetTypes[1],
    name: "Adobe Creative Cloud",
    category: "it",
    status: "assigned",
    organizationId: "org-1",
    locationId: "loc-1",
    departmentId: "dept-2",
    expiryDate: new Date("2025-02-01"),
    properties: {
      Vendor: "Adobe",
      "License Key": "ADOBE-XXXXX-XXXXX",
      Seats: 10,
      "Renewal Date": "2025-02-01",
    },
    createdAt: new Date("2023-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "asset-5",
    assetTypeId: "type-3",
    assetType: assetTypes[2],
    name: "Standing Desk",
    serialNumber: "DESK-001",
    category: "it",
    status: "assigned",
    organizationId: "org-1",
    locationId: "loc-1",
    departmentId: "dept-1",
    properties: {
      Type: "Desk",
      Material: "Wood & Metal",
      Color: "Walnut",
    },
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2023-01-20"),
  },
  {
    id: "asset-6",
    assetTypeId: "type-4",
    assetType: assetTypes[3],
    name: "HP Black Toner",
    category: "consumables",
    status: "available",
    organizationId: "org-1",
    locationId: "loc-2",
    departmentId: "dept-3",
    expiryDate: new Date("2025-06-30"),
    properties: {
      Color: "Black",
      "Compatible Printer": "HP LaserJet Pro M404",
      "Page Yield": 3000,
    },
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
];

// Mock Asset Movements
export const assetMovements: AssetMovement[] = [
  {
    id: "mov-1",
    assetId: "asset-1",
    fromDepartmentId: "dept-2",
    toDepartmentId: "dept-1",
    fromUserId: "user-4",
    toUserId: "user-2",
    reason: "Employee transfer to Engineering team",
    approvedById: "user-3",
    status: "approved",
    createdAt: new Date("2024-01-10"),
    completedAt: new Date("2024-01-11"),
  },
  {
    id: "mov-2",
    assetId: "asset-2",
    fromLocationId: "loc-2",
    toLocationId: "loc-1",
    reason: "Office consolidation",
    status: "pending",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "mov-3",
    assetId: "asset-5",
    fromDepartmentId: "dept-1",
    toDepartmentId: "dept-4",
    reason: "Furniture redistribution",
    approvedById: "user-9",
    status: "approved",
    createdAt: new Date("2024-01-08"),
    completedAt: new Date("2024-01-09"),
  },
];

// Mock Movements in table-friendly format
export const mockMovements = [
  {
    id: "mov-1",
    assetId: "asset-1",
    type: "transfer" as const,
    fromLocation: "West Coast Office",
    fromDepartment: "Marketing",
    toLocation: "Headquarters",
    toDepartment: "Engineering",
    requestedBy: "John Anderson",
    requestedDate: "2024-01-10",
    status: "approved" as const,
    approvedBy: "Michael Rodriguez",
    notes: "Employee transfer to Engineering team",
  },
  {
    id: "mov-2",
    assetId: "asset-2",
    type: "transfer" as const,
    fromLocation: "West Coast Office",
    toLocation: "Headquarters",
    requestedBy: "Sarah Chen",
    requestedDate: "2024-01-15",
    status: "pending" as const,
    notes: "Office consolidation",
  },
  {
    id: "mov-3",
    assetId: "asset-5",
    type: "transfer" as const,
    fromLocation: "Headquarters",
    fromDepartment: "Engineering",
    toLocation: "Headquarters",
    toDepartment: "Human Resources",
    requestedBy: "Emily Watson",
    requestedDate: "2024-01-08",
    status: "completed" as const,
    approvedBy: "David Kim",
    notes: "Furniture redistribution",
  },
  {
    id: "mov-4",
    assetId: "asset-3",
    type: "checkout" as const,
    fromLocation: "Headquarters",
    fromDepartment: "IT Storage",
    toLocation: "Headquarters",
    toDepartment: "Marketing",
    requestedBy: "Emily Watson",
    requestedDate: "2024-01-20",
    status: "pending" as const,
    notes: "New hire software assignment",
  },
  {
    id: "mov-5",
    assetId: "asset-6",
    type: "maintenance" as const,
    fromLocation: "West Coast Office",
    fromDepartment: "Sales",
    toLocation: "Headquarters",
    toDepartment: "IT Support",
    requestedBy: "Michael Rodriguez",
    requestedDate: "2024-01-18",
    status: "approved" as const,
    approvedBy: "John Anderson",
    notes: "Printer cartridge replacement needed",
  },
];

// Dashboard Stats
export const dashboardStats: DashboardStats = {
  totalAssets: 2547,
  assetsByCategory: {
    physical: 1823,
    digital: 342,
    consumable: 287,
    rechargeable: 95,
  },
  assetsByStatus: {
    available: 892,
    assigned: 1423,
    in_stock: 0,
    in_use: 0,
    in_maintenance: 127,
    retired: 89,
    lost: 16,
  },
  expiringAssets: 23,
  recentMovements: assetMovements,
  assetsWithGaps: 8,
};

// Users for assignment - with full reporting hierarchy
export const users: User[] = [
  currentUser,
  {
    id: "user-2",
    name: "Sarah Chen",
    email: "sarah@acmecorp.com",
    role: "cinema_user",
    organizationId: "org-1",
    locationId: "loc-1",
    departmentId: "dept-1",
    reportsToId: "user-4",
    approverIds: ["user-4", "user-3", "user-12", "user-1"],
  },
  {
    id: "user-3",
    name: "Michael Rodriguez",
    email: "michael@acmecorp.com",
    role: "location_hod",
    organizationId: "org-1",
    locationId: "loc-1",
    departmentId: "dept-1",
    reportsToId: "user-12",
    approverIds: ["user-12", "user-1"],
    canApproveTransfers: true,
    canApproveDisposals: false,
  },
  {
    id: "user-4",
    name: "Emily Watson",
    email: "emily@acmecorp.com",
    role: "reporting_person",
    organizationId: "org-1",
    locationId: "loc-1",
    departmentId: "dept-2",
    reportsToId: "user-3",
    approverIds: ["user-3", "user-12", "user-1"],
  },
  {
    id: "user-5",
    name: "David Kim",
    email: "david@acmecorp.com",
    role: "location_hod",
    organizationId: "org-1",
    locationId: "loc-1",
    departmentId: "dept-2",
    reportsToId: "user-12",
    approverIds: ["user-12", "user-1"],
    canApproveTransfers: true,
  },
  {
    id: "user-12",
    name: "Robert Taylor",
    email: "robert@acmecorp.com",
    role: "regional_admin",
    organizationId: "org-1",
    regionId: "region-1",
    reportsToId: "user-1",
    approverIds: ["user-1"],
    canApproveTransfers: true,
    canApproveDisposals: true,
  },
  {
    id: "user-13",
    name: "Jennifer Lee",
    email: "jennifer@acmecorp.com",
    role: "regional_admin",
    organizationId: "org-1",
    regionId: "region-2",
    reportsToId: "user-1",
    approverIds: ["user-1"],
    canApproveTransfers: true,
    canApproveDisposals: true,
  },
  {
    id: "user-14",
    name: "William Brown",
    email: "william@acmecorp.com",
    role: "regional_admin",
    organizationId: "org-1",
    regionId: "region-3",
    reportsToId: "user-1",
    approverIds: ["user-1"],
    canApproveTransfers: true,
    canApproveDisposals: true,
  },
];

// Workflow Requests (Transfer/Disposal/Buyback)
export const workflowRequests: WorkflowRequest[] = [
  {
    id: "wf-1",
    assetId: "asset-1",
    requestType: "transfer",
    currentStage: "regional",
    requestedBy: "user-4",
    requestedAt: new Date("2024-01-15"),
    reason: "Projector needs to be moved to new screen",
    documents: ["transfer-form-001.pdf"],
    serialNumbers: ["PRJ-2023-001"],
    approvalHistory: [
      {
        stage: "cinema",
        approvedBy: "user-4",
        approvedAt: new Date("2024-01-15"),
        status: "approved",
        comments: "Initiated transfer request",
      },
      {
        stage: "regional",
        status: "pending",
      },
    ],
  },
  {
    id: "wf-2",
    assetId: "asset-6",
    requestType: "disposal",
    currentStage: "ho",
    requestedBy: "user-2",
    requestedAt: new Date("2024-01-10"),
    reason: "Equipment beyond repair - end of life",
    documents: ["disposal-request.pdf", "condition-report.pdf"],
    serialNumbers: ["EQP-2019-045"],
    approvalHistory: [
      {
        stage: "cinema",
        approvedBy: "user-2",
        approvedAt: new Date("2024-01-10"),
        status: "approved",
        comments: "Equipment is no longer functional",
      },
      {
        stage: "regional",
        approvedBy: "user-3",
        approvedAt: new Date("2024-01-12"),
        status: "approved",
        comments: "Verified condition, recommend disposal",
      },
      {
        stage: "ho",
        status: "pending",
      },
    ],
  },
  {
    id: "wf-3",
    assetId: "asset-3",
    requestType: "buyback",
    currentStage: "completed",
    requestedBy: "user-5",
    requestedAt: new Date("2024-01-05"),
    reason: "Employee wishes to purchase laptop at depreciated value",
    documents: ["buyback-agreement.pdf"],
    serialNumbers: ["LPT-2021-089"],
    approvalHistory: [
      {
        stage: "cinema",
        approvedBy: "user-5",
        approvedAt: new Date("2024-01-05"),
        status: "approved",
      },
      {
        stage: "regional",
        approvedBy: "user-3",
        approvedAt: new Date("2024-01-07"),
        status: "approved",
      },
      {
        stage: "ho",
        approvedBy: "user-1",
        approvedAt: new Date("2024-01-09"),
        status: "approved",
        comments: "Approved at $450 depreciated value",
      },
    ],
    finalDecision: "buyback",
    completedAt: new Date("2024-01-09"),
  },
];

// Notifications
export const notifications: Notification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    type: "approval_required",
    title: "Disposal Request Pending",
    message: "A disposal request for HP Printer requires your approval",
    relatedAssetId: "asset-6",
    relatedWorkflowId: "wf-2",
    read: false,
    acknowledged: false,
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "notif-2",
    userId: "user-3",
    type: "transfer",
    title: "Asset Transferred",
    message: "MacBook Pro has been transferred to Engineering department",
    relatedAssetId: "asset-1",
    read: true,
    acknowledged: true,
    acknowledgedAt: new Date("2024-01-11"),
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "notif-3",
    userId: "user-2",
    type: "ownership_change",
    title: "New Asset Assigned",
    message: "You have been assigned a new Dell XPS 15 laptop",
    relatedAssetId: "asset-2",
    read: false,
    acknowledged: false,
    createdAt: new Date("2024-01-16"),
  },
  {
    id: "notif-4",
    userId: "user-1",
    type: "acknowledgement",
    title: "Acknowledgement Required",
    message: "Please acknowledge receipt of transferred projector",
    relatedAssetId: "asset-1",
    read: true,
    acknowledged: false,
    createdAt: new Date("2024-01-14"),
  },
];

// Audit Logs (Immutable)
export const auditLogs: AuditLog[] = [
  {
    id: "log-1",
    entityType: "asset",
    entityId: "asset-1",
    action: "created",
    performedBy: "user-1",
    details: { name: "MacBook Pro 16-inch", category: "it" },
    timestamp: new Date("2023-06-15"),
    immutable: true,
  },
  {
    id: "log-2",
    entityType: "transfer",
    entityId: "mov-1",
    action: "initiated",
    performedBy: "user-4",
    details: { fromDepartment: "Marketing", toDepartment: "Engineering" },
    timestamp: new Date("2024-01-10"),
    immutable: true,
  },
  {
    id: "log-3",
    entityType: "approval",
    entityId: "wf-2",
    action: "approved",
    performedBy: "user-3",
    details: { stage: "regional", requestType: "disposal" },
    timestamp: new Date("2024-01-12"),
    immutable: true,
  },
  {
    id: "log-4",
    entityType: "disposal",
    entityId: "wf-3",
    action: "completed",
    performedBy: "user-1",
    details: { decision: "buyback", value: 450 },
    timestamp: new Date("2024-01-09"),
    immutable: true,
  },
];

// Asset Requests - Request-based workflow
export const assetRequests: AssetRequest[] = [
  {
    id: "req-001",
    requestNumber: "REQ-2024-001",
    type: "transfer",
    status: "in_review",
    priority: "medium",
    assetId: "asset-1",
    fromLocationId: "loc-1",
    toLocationId: "loc-2",
    fromDepartmentId: "dept-1",
    toDepartmentId: "dept-3",
    requestedBy: "user-4",
    requestedAt: new Date("2024-01-15"),
    reason: "Asset needed at West Coast Office for new project",
    justification: "The engineering team at West Coast requires additional computing resources for the new client project.",
    documents: ["transfer-justification.pdf"],
    currentApprovalLevel: "regional",
    approvalChain: [
      {
        level: "location",
        approverId: "user-3",
        approverName: "Michael Rodriguez",
        approverRole: "location_hod",
        status: "approved",
        actionAt: new Date("2024-01-16"),
        comments: "Approved - asset is available for transfer",
      },
      {
        level: "regional",
        approverId: "user-12",
        approverName: "Robert Taylor",
        approverRole: "regional_admin",
        status: "pending",
      },
      {
        level: "ho",
        approverId: "user-1",
        approverName: "John Anderson",
        approverRole: "ho_admin",
        status: "pending",
      },
    ],
    requiresAcknowledgement: true,
  },
  {
    id: "req-002",
    requestNumber: "REQ-2024-002",
    type: "dispose",
    status: "pending",
    priority: "low",
    assetId: "asset-6",
    requestedBy: "user-2",
    requestedAt: new Date("2024-01-18"),
    reason: "Equipment beyond repair - end of useful life",
    justification: "The printer has multiple hardware failures and repair costs exceed replacement value.",
    documents: ["condition-report.pdf", "repair-estimate.pdf"],
    currentApprovalLevel: "location",
    approvalChain: [
      {
        level: "location",
        approverId: "user-3",
        approverName: "Michael Rodriguez",
        approverRole: "location_hod",
        status: "pending",
      },
      {
        level: "regional",
        approverId: "user-12",
        approverName: "Robert Taylor",
        approverRole: "regional_admin",
        status: "pending",
      },
      {
        level: "ho",
        approverId: "user-1",
        approverName: "John Anderson",
        approverRole: "ho_admin",
        status: "pending",
      },
    ],
    requiresAcknowledgement: false,
  },
  {
    id: "req-003",
    requestNumber: "REQ-2024-003",
    type: "buyback",
    status: "approved",
    priority: "medium",
    assetId: "asset-2",
    requestedBy: "user-5",
    requestedAt: new Date("2024-01-10"),
    reason: "Employee wishes to purchase laptop at depreciated value",
    justification: "Employee is leaving the company and wishes to retain the assigned laptop.",
    documents: ["buyback-agreement.pdf", "depreciation-calc.pdf"],
    currentApprovalLevel: "ho",
    approvalChain: [
      {
        level: "location",
        approverId: "user-3",
        approverName: "Michael Rodriguez",
        approverRole: "location_hod",
        status: "approved",
        actionAt: new Date("2024-01-11"),
        comments: "Approved - asset in good condition",
      },
      {
        level: "regional",
        approverId: "user-12",
        approverName: "Robert Taylor",
        approverRole: "regional_admin",
        status: "approved",
        actionAt: new Date("2024-01-13"),
        comments: "Approved - buyback value is fair",
      },
      {
        level: "ho",
        approverId: "user-1",
        approverName: "John Anderson",
        approverRole: "ho_admin",
        status: "approved",
        actionAt: new Date("2024-01-15"),
        comments: "Approved at $450 depreciated value",
      },
    ],
    finalApprovedBy: "user-1",
    finalApprovedAt: new Date("2024-01-15"),
    completedAt: new Date("2024-01-15"),
    requiresAcknowledgement: false,
  },
  {
    id: "req-004",
    requestNumber: "REQ-2024-004",
    type: "assign",
    status: "pending",
    priority: "high",
    assetId: "asset-2",
    toUserId: "user-2",
    requestedBy: "user-4",
    requestedAt: new Date("2024-01-20"),
    reason: "New employee requires laptop for onboarding",
    currentApprovalLevel: "location",
    approvalChain: [
      {
        level: "location",
        approverId: "user-3",
        approverName: "Michael Rodriguez",
        approverRole: "location_hod",
        status: "pending",
      },
    ],
    requiresAcknowledgement: true,
  },
  {
    id: "req-005",
    requestNumber: "REQ-2024-005",
    type: "create",
    status: "draft",
    priority: "medium",
    assetDetails: {
      name: "Dell Precision 5570",
      category: "it",
      assetTypeId: "type-1",
      serialNumber: "DELL-5570-2024-001",
      properties: {
        Brand: "Dell",
        Model: "Precision 5570",
        "RAM (GB)": 32,
        "Storage (GB)": 1024,
        "Operating System": "Windows 11",
      },
    },
    requestedBy: "user-4",
    requestedAt: new Date("2024-01-22"),
    reason: "New workstation required for design team expansion",
    currentApprovalLevel: "location",
    approvalChain: [],
    requiresAcknowledgement: false,
  },
];

// Approval Routing Rules - Configurable per organization
export const approvalRoutingRules: ApprovalRoutingRule[] = [
  {
    id: "rule-1",
    organizationId: "org-1",
    name: "Standard Transfer Approval",
    description: "Default approval flow for asset transfers",
    isActive: true,
    conditions: {
      requestTypes: ["transfer"],
    },
    approvalLevels: [
      {
        level: "location",
        required: true,
        approverType: "role",
        approverRoles: ["location_hod"],
      },
      {
        level: "regional",
        required: true,
        approverType: "role",
        approverRoles: ["regional_admin"],
      },
      {
        level: "ho",
        required: true,
        approverType: "role",
        approverRoles: ["ho_admin"],
      },
    ],
    allowParallelApproval: false,
    requireAllApprovers: true,
    escalationDays: 3,
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "rule-2",
    organizationId: "org-1",
    name: "Disposal Approval",
    description: "Approval flow for asset disposal and buyback",
    isActive: true,
    conditions: {
      requestTypes: ["dispose", "buyback"],
    },
    approvalLevels: [
      {
        level: "location",
        required: true,
        approverType: "role",
        approverRoles: ["location_hod"],
      },
      {
        level: "regional",
        required: true,
        approverType: "role",
        approverRoles: ["regional_admin"],
      },
      {
        level: "ho",
        required: true,
        approverType: "role",
        approverRoles: ["ho_admin"],
      },
    ],
    allowParallelApproval: false,
    requireAllApprovers: true,
    escalationDays: 5,
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "rule-3",
    organizationId: "org-1",
    name: "Assignment Approval",
    description: "Approval flow for asset assignments - location-level only",
    isActive: true,
    conditions: {
      requestTypes: ["assign"],
    },
    approvalLevels: [
      {
        level: "location",
        required: true,
        approverType: "role",
        approverRoles: ["location_hod", "reporting_person"],
      },
    ],
    allowParallelApproval: false,
    requireAllApprovers: false,
    escalationDays: 2,
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "rule-4",
    organizationId: "org-1",
    name: "High-Value Asset Transfer",
    description: "Special approval for assets over $5000",
    isActive: true,
    conditions: {
      requestTypes: ["transfer", "dispose", "buyback"],
      minValue: 5000,
    },
    approvalLevels: [
      {
        level: "location",
        required: true,
        approverType: "role",
        approverRoles: ["location_hod"],
      },
      {
        level: "regional",
        required: true,
        approverType: "role",
        approverRoles: ["regional_admin"],
      },
      {
        level: "ho",
        required: true,
        approverType: "user",
        approverUserIds: ["user-1"],
      },
    ],
    allowParallelApproval: false,
    requireAllApprovers: true,
    escalationDays: 2,
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

// Export aliases for backward compatibility
export const mockUsers = users;
export const mockLocations = locations;
export const mockDepartments = departments;
export const mockAssets = assets;
export const mockRegions = regions;
